# template.yaml

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Chromaxen Backend Serverless Application

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.9
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowHeaders: "'*'"
      AllowMethods: "'GET,POST,OPTIONS'"

Resources:
  ChromaxenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: main.handler
      PackageType: Zip
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource: "*"
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: HighScores

      Events:
        WinState:
          Type: Api
          Properties:
            Path: /api/win_state
            Method: post
        WinStates:
          Type: Api
          Properties:
            Path: /api/win_states
            Method: get
    Metadata:
      BuildMethod: python3.9
      BuildProperties:
        Exclude:
          - "Dockerfile*"
          - ".dockerignore"
          - ".gitignore"
          - ".samignore"
          - "*.pyc"
          - "__pycache__/*"
          - "dockerfiles/**"
