# .github/workflows/ci-cd.yml

name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Frontend tests

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci
      
      - name: Run frontend tests
        working-directory: frontend
        run: npm run test

      # Backend tests

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Run tests
        working-directory: backend
        env:
          TESTING: "1"
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest tests/

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Install Terraform
        run: |
          sudo apt-get install -y gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install -y terraform

      - name: Build Lambda deployment package
        run: |
          chmod +x build_deployment_package.sh
          ./build_deployment_package.sh

      - name: Initialize Terraform
        run: |
          terraform init

      - name: Apply Terraform changes
        run: |
          terraform apply -auto-approve

      - name: Deploy Frontend to S3
        env:
          AWS_REGION: us-east-2
          S3_BUCKET: chromaxen-dev-test
        run: |
          aws s3 sync frontend/ s3://$S3_BUCKET/ --delete --cache-control "max-age=0, no-cache, no-store, must-revalidate"
